- name: Update and upgrade apt packages
  hosts: agent
  become: true

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist

- name: Install Kubernetes Server
  hosts: agent
  become: true

  tasks:
    - name: Retrieve K3s node token
      ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      when: inventory_hostname == "k3s-soniiit-server01"

    - name: Install K3s on Agents
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" INSTALL_K3S_CHANNEL=latest sh -s - --server=https://{{ kubernetes_vip }}:6443 --token={{ hostvars['k3s-soniiit-server01']['k3s_token'].stdout }}
