apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: soniiit-net-production
  namespace: teleport-cluster
spec:
  secretName: soniiit-net-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "teleport.soniiit.net"
  dnsNames:
    - "teleport.soniiit.net"
    - "*.teleport.soniiit.net"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-teleport-cluster-https-redirect
  namespace: teleport-cluster
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-teleport-cluster-security
  namespace: teleport-cluster
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: traefik-teleport-cluster-transport
  namespace: teleport-cluster
spec:
  serverName: traefik
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: traefik-teleport-cluster-tlsoptions
  namespace: teleport-cluster
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-teleport-cluster-websecure
  namespace: teleport-cluster
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`teleport.soniiit.net`)
      services:
        - name: teleport-cluster
          port: 443
          serversTransport: traefik-teleport-cluster-transport
      middlewares:
        - name: traefik-teleport-cluster-security
  tls:
    secretName: soniiit-net-production-tls
    options:
      name: traefik-teleport-cluster-tlsoptions
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport-cluster-wildcard-ingress
  namespace: teleport-cluster
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  tls:
  - hosts:
    - "*.teleport.soniiit.net"
    secretName: soniiit-net-production-tls
  rules:
  - host: "*.teleport.soniiit.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teleport-cluster
            port:
              number: 443
