version: v2
teleport:
  nodename: teleport.soniiit.net
  data_dir: /var/lib/teleport
  auth_token: "hiertoken"
  log:
    output: stderr
    severity: INFO
    format:
      output: text

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: teleport.soniiit.net
  # -- (Optional) Passwordless Authentication
  # authentication:
  #   type: local
  #   second_factor: on
  #   webauthn:
  #     rp_id: your-server-url
  #   connector_name: passwordless
  # -- (Optional) Teleport Assist
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

ssh_service:
  enabled: "yes"
  lables:
    env: node

proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  # -- (Optional) when using reverse proxy
  public_addr: ['teleport.soniiit.net:443']
  https_keypairs: []
  acme: {}
  # --(Optional) ACME
  # acme:
  #   enabled: "yes"
  #   email: your-email-address
  # -- (Optional) Teleport Assist
  # assist:
  #   openai:
  #     api_token_path: /etc/teleport/openai_key

app_service:
  enabled: no
  # -- (Optional) App Service
  # enabled: yes
  # apps:
  #   - name: "Homepage"
  #     uri: "http://192.168.178.21:3001"
  #     insecure_skip_verify: true
