version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3350:3306"
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8040:80"
    environment:
      - "PMA_ARBITRARY=1"