id: Check-Disk-Space
namespace: ansible
labels:
  Project: Homelab
  Mode: Auto

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    inputFiles:
        inventory.yaml: "{{ read('inventory.ini') }}"
        check-disk-space.yaml: "{{ read('check-disk-space.yaml') }}"
        id_rsa: "{{ secret('SSH_KEY') }}"

  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
      user: "1000"
    containerImage: cytopia/ansible:latest-tools
    commands:
    - ansible-playbook -i inventory.yaml --key-file id_rsa check-disk-space.yaml

triggers:
- id: every_15_minutes
  type: io.kestra.plugin.core.trigger.Schedule
  cron: '*/15 * * * *'

disabled: false
