id: Check-Disk-Space
namespace: ansible
labels:
  Project: Homelab
  Mode: Auto

tasks:
- id: setup
  type: io.kestra.core.tasks.flows.WorkingDirectory
  tasks:
  - id: local_files
    type: io.kestra.core.tasks.storages.LocalFiles
    inputs:
      inventory.yaml: "{{ read('inventory.yaml') }}"
      check-disk-space.yaml: "{{ read('check-disk-space.yaml') }}"
      id_rsa: "{{ secret('SSH_KEY') }}"

  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    docker:
      image: cytopia/ansible:latest-tools
      pullPolicy: IF_NOT_PRESENT
      user: "1000"
    commands:
    - ansible-playbook -i inventory.yaml --key-file id_rsa check-disk-space.yaml

triggers:
- id: check-disk-space
  type: io.kestra.core.models.triggers.types.Schedule
  cron: "*/15 * * * *"
