id: Example
namespace: ansible
labels:
  Project: Homelab
  Mode: Auto/Manual

tasks:
- id: setup
  type: io.kestra.core.tasks.flows.WorkingDirectory
  tasks:
  - id: local_files
    type: io.kestra.core.tasks.storages.LocalFiles
    inputs:
      inventory.yaml: "{{ read('inventory.yaml') }}"
      playbook.yaml: "{{ read('playbook.yaml') }}"
      id_rsa: "{{ secret('SSH_KEY') }}"

  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    docker:
      image: cytopia/ansible:latest-tools
      pullPolicy: IF_NOT_PRESENT
      user: "1000"
    beforeCommands:
    - apk add --no-cache sshpass
    - chmod 600 id_rsa
    commands:
    - ansible-playbook -i inventory.yaml --key-file id_rsa playbook.yaml

triggers:
- id: example
  type: io.kestra.core.models.triggers.types.Schedule
  cron: "30 20 * * *" #Every Day at 20:30
  cron: "*/15 * * * *" #Every 15 Minutes
