id: Reboot-Required-Linux
namespace: ansible
labels:
  Project: Homelab
  Mode: Auto

tasks:
- id: setup
  type: io.kestra.plugin.core.flow.WorkingDirectory
  tasks:
  - id: local_files
    type: io.kestra.plugin.core.storage.LocalFiles
    inputs:
      inventory.yaml: "{{ read('inventory.yaml') }}"
      reboot-required-linux.yaml: "{{ read('reboot-required-linux.yaml') }}"
      id_rsa: "{{ secret('SSH_KEY') }}"

  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    containerImage: cytopia/ansible:latest-tools
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
    beforeCommands:
    - apk add --no-cache sshpass
    - chmod 600 id_rsa
    commands:
    - ansible-playbook -i inventory.yaml --key-file id_rsa reboot-required-linux.yaml

triggers:
- id: daily_check_reboot
  type: io.kestra.plugin.core.trigger.Schedule
  cron: "30 22 * * *"

disabled: false
