version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet

  php-fpm:
    image: php:fpm-alpine
    volumes:
      - ./data:/var/www/html
    networks:
      - webnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: meinpasswort
      MYSQL_DATABASE: meineDatenbank
      MYSQL_USER: benutzer
      MYSQL_PASSWORD: benutzerpasswort
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data: