version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - LOG_LEVEL=info
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
      - ./homepage/images:/app/images # (optional) For custom background images
      - ./homepage/icons:/app/icons # (optional) For custom icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped