version: "3.7"

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pass
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pass
      - MYSQL_ROOT_PASSWORD=root_pass
    volumes:
      - zabbix-db:/var/lib/mysql

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "8080:80"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pass
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server

volumes:
  zabbix-db:
