# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: portainer/portainer-ce
  tag: 2.22.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: ClusterIP
  httpPort: 9000
  httpNodePort:
  edgePort: 8000

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: portainer.home.soniiit.net
      paths:
        - path: "/"
  tls:
    - secretName: home-soniiit-net-selfsigned-tls
      hosts:
        - portainer.home.soniiit.net

resources: {}

persistence:
  size: "1Gi"
  annotations: {}
