all:
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  children:
    docker:
      hosts:
        docker-srv-03:
          ansible_host: 192.168.178.40
          ansible_user: soniiit
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
