---
- name: Festplatte einrichten und mounten
  hosts: k3s_cluster
  become: true
  vars:
    device_path: /dev/vdb
    mount_point: /mnt/kubernetes
    filesystem: ext4
    partition_number: 1

  tasks:
    - name: Partition erstellen
      parted:
        device: "{{ device_path }}"
        number: 1
        state: present
        part_end: "100%"

    - name: Dateisystem formatieren
      filesystem:
        fstype: "{{ filesystem }}"
        dev: "{{ device_path }}1"

    - name: Mount-Verzeichnis erstellen
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Festplatte mounten
      command: "mount {{ device_path }}{{ partition_number }} {{ mount_point }}"
      become: true
      
    - name: Eintrag in fstab hinzufügen
      lineinfile:
        path: /etc/fstab
        line: "{{ device_path }}{{ partition_number }} {{ mount_point }}    {{ filesystem }}    defaults        0       0"
        state: present
      become: true
