- name: Check if system reboot is required
  hosts: all
  become: true

  tasks:
  - name: Check if system reboot is required
    become: true
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Send discord message when reboot is required
    uri:
      url: "https://discord.com/api/webhooks/xyz/xyz"
      method: POST
      body_format: json
      body: '{"content": "> Reboot is required on {{ inventory_hostname }}!"}'
      headers:
        Content-Type: application/json
      status_code: 204
    when: reboot_required.stat.exists
