- name: Uninstall Teleport
  hosts: all
  become: true
  tasks:
    - name: Remove Teleport package
      apt:
        name: teleport
        state: absent
        purge: true
      when: ansible_os_family == "Debian"

    - name: Remove Teleport package (RHEL/CentOS)
      yum:
        name: teleport
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Teleport configuration directory
      file:
        path: /etc/teleport
        state: absent

    - name: Remove Teleport data directory
      file:
        path: /var/lib/teleport
        state: absent

    - name: Kill Teleport process
      shell: pkill -f teleport
      ignore_errors: yes

    - name: Entferne Teleport Binärdateien
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/bin/teleport
        - /usr/local/bin/tctl 
        - /usr/local/bin/tsh

    - name: Entferne Teleport Konfigurationsdatei
      file:
        path: /etc/teleport.yaml
        state: absent

