version: "3.3"
networks:
  traefik-nw:
    external: true
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.12
    container_name: uptime-kuma
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./uptime-kuma-data:/app/data
    networks:
      - traefik-nw
    ports:
      - 3001:3001
    restart: unless-stopped