# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: false
    memory: false

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23

- search:
    provider: google
    target: _blank
