apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.soniiit.net`)
      kind: Rule
      services:
        - name: authentik-server
          port: 443
  tls:
    secretName: soniiit-net-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: soniiit-net-production
  namespace: authentik
spec:
  secretName: soniiit-net-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "authentik.soniiit.net"
