version: "3.3"
services:
  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    container_name: kestra
    stdin_open: true
    tty: true
    ports:
      - 1337:8080
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-compose/kestra/tmp:/tmp
      - /mnt/docker-compose/kestra/data/:/app/data
    command: server local
    restart: unless-stopped
    environment:
      - SECRET_SSH_KEY=${SECRET_SSH_KEY}
      - SECRET_TF_PVE_API_TOKEN=${SECRET_TF_PVE_API_TOKEN}
      - SECRET_TF_ID_TOKEN=${SECRET_TF_ID_TOKEN}
      - SECRET_TSIG_KEY=${SECRET_TSIG_KEY}
      - SECRET_TG_API_TOKEN=${SECRET_TG_API_TOKEN}
      - KESTRA_TUTORIAL_FLOWS_ENABLED=false
networks: {}
