- IOT-Devices:
  - Epson Drucker (WZ):
    - icon: https://cdn-icons-png.flaticon.com/512/882/882706.png
      href: http://drucker-wz.home.soniiit.net/PRESENTATION/HTML/TOP/INDEX.HTML
  - Brother Drucker (Iris):
    - icon: https://logos-world.net/wp-content/uploads/2023/01/Brother-Logo.png
      href: https://drucker-iris.home.soniiit.net/home/status.html

- Cloud Services:
  - Confluence:
    - icon: https://soniiit.atlassian.net/wiki/s/1238699948/6452/c4fd8688f220479d537f6a0bca23e41d59d1be40/1/_/favicon-update.ico
      href: https://soniiit.atlassian.net/wiki/home
  - AFFiNE:
    - icon: https://affine.pro/favicon-96.png
      href: https://app.affine.pro
  - Dockerhub:
    - icon: https://hub.docker.com/favicon.ico
      href: https://hub.docker.com/
  - Artifacthub:
    - icon: https://artifacthub.io/static/media/logo192_v2.png
      href: https://artifacthub.io/
  - Cloudflare:
    - icon: cloudflare.png
      href: https://dash.cloudflare.com
  - CrowdSec:
    - icon: https://avatars.githubusercontent.com/u/63284097?s=280&v=4
      href: https://app.crowdsec.net/
  - Linode:
    - icon: https://cloud.linode.com/favicon.ico
      href: https://cloud.linode.com/
  - Twingate:
    - icon: https://media.licdn.com/dms/image/C4D0BAQHDl7hoI11gZg/company-logo_200_200/0/1649876306356/twingate_logo?e=2147483647&v=beta&t=zurgqAiwMiU0RktNbdCHD3T1qJ4hka7aLYw2mkGEtdU
      href: https://soniiit.twingate.com
  - Trade Republic:
    - icon: https://companieslogo.com/img/orig/traderepublic.D-de64dfeb.png?t=1700800010
      href: https://app.traderepublic.com/
  - Cloud HashiCorp:
    - icon: https://portal.cloud.hashicorp.com/favicon.svg
      href: https://portal.cloud.hashicorp.com/
  - MS365 Admin:
    - icon: https://res.cdn.office.net/admincenter/admin-content/images/favicon_fluent.ico
      href: https://admin.microsoft.com/Adminportal/Home#/homepage
  - Ubiquiti:
    - icon: https://account.ui.com/static/favicon.ico
      href: https://account.ui.com/

- Local Services:
  - Dockge:
    - icon: https://dockge.kuma.pet/icon.svg
      href: https://dockge.home.soniiit.net
  - Kestra:
    - icon: https://kestra-io.gallerycdn.vsassets.io/extensions/kestra-io/kestra/0.0.1/1692285562923/Microsoft.VisualStudio.Services.Icons.Default
      href: https://kestra.home.soniiit.net

- Local Cloud Services:
  - SoniiiT:
    - icon: https://2.gravatar.com/userimage/251867332/7fdbed615fb74f9b2adbca311c305931?size=256
      href: https://soniiit.net
  - Docs:
    - icon: https://2.gravatar.com/userimage/251867332/7fdbed615fb74f9b2adbca311c305931?size=256
      href: https://docs.soniiit.net
  - Fireshare:
    - icon: https://v.fireshare.net/favicon.ico
      href: https://fireshare.soniiit.net
  - Authentik:
    - icon: https://goauthentik.io/img/icon.png
      href: https://authentik.soniiit.net
  - Teleport:
    - icon: https://ugc.production.linktr.ee/wXEaEAdBSneQwAwBfO3n_zitU1eq5y26VYyyH?io=true&size=avatar-v3_0
      href: https://teleport.soniiit.net/
  - Kasm Workspaces:
    - icon: https://kasmweb.com/assets/fav/favicon-32x32.png
      href: https://kasm.soniiit.net
