    - Networking:
      - FritzBox Main:
          href: http://192.168.178.1
          icon: avmfritzbox.png
          description: Fritz!Box Main
          siteMonitor: http://192.168.178.1
          widget:
            type: fritzbox
            url: http://192.168.178.1
      - FritzBox Tony:
          href: http://192.168.178.2
          icon: avmfritzbox.png
          description: Fritz!Box Tony
          siteMonitor: http://192.168.178.2
      - Traefik-MGM:
          href: https://traefik-mgm.home.soniiit.net/dashboard/
          icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
          description: Traefik-MGM on Docker-SRV-MGM
          siteMonitor: http://192.168.178.20:9090
          widget:
            type: traefik
            url: https://traefik-mgm.home.soniiit.net
      - Traefik-01:
          href: https://traefik-01.home.soniiit.net/dashboard/
          icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
          description: Traefik-01 on Docker-SRV-MGM
          siteMonitor: http://192.168.178.21:9090
          widget:
            type: traefik
            url: https://traefik-01.home.soniiit.net
      - Traefik-02:
          href: https://traefik-02.home.soniiit.net/dashboard/
          icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
          description: Traefik-02 on Docker-SRV-02
          siteMonitor: http://192.168.178.22:9090
          widget:
            type: traefik
            url: https://traefik-02.home.soniiit.net
    
    - Infrastructure and Data:
      - Proxmox:
          href: https://proxmox.home.soniiit.net:8006
          icon: proxmox.png
          description: PVE-SRV-01
          siteMonitor: https://proxmox.home.soniiit.net:8006
          widget:
            type: proxmox
            url: https://proxmox.home.soniiit.net:8006
            username: 
            password: 
            node: pve-srv-01
      - Nextcloud:
          href: https://nextcloud.soniiit.net
          icon: https://cdn.icon-icons.com/icons2/2108/PNG/512/nextcloud_icon_130873.png
          description: Nextcloud on Docker-SRV-02
          siteMonitor: https://nextcloud.soniiit.net
      - TrueNAS:
          href: https://truenas.home.soniiit.net
          icon: truenas.png
          description: NAS-TNAS-01 on PVE-SRV-01
          siteMonitor: https://truenas.home.soniiit.net
          widget:
              type: truenas
              url: https://truenas.home.soniiit.net
              key: 
              enablePools: false
    
    - Management:
      - Portainer-MGM:
          href: https://portainer.home.soniiit.net/#!/2/docker/dashboard
          icon: portainer.png
          description: Portainer on Docker-SRV-MGM
          siteMonitor: https://portainer.home.soniiit.net
          widget:
            type: portainer
            url: https:portainer.home.soniiit.net
            env: 2
            key: 
      - Portainer-01:
          href: https://portainer.home.soniiit.net/#!/4/docker/dashboard
          icon: portainer.png
          description: Portainer on Docker-SRV-MGM
          siteMonitor: https://portainer.home.soniiit.net
          widget:
            type: portainer
            url: https://portainer.home.soniiit.net
            env: 4
            key: 
      - Portainer-02:
          href: https://portainer.home.soniiit.net/#!/5/docker/dashboard
          icon: portainer.png
          description: Portainer on Docker-SRV-MGM
          siteMonitor: https://portainer.home.soniiit.net
          widget:
            type: portainer
            url: https://portainer.home.soniiit.net
            env: 5
            key: 
    
    - Monitoring:
      - UptimeKuma:
          href: https://uptime.home.soniiit.net
          description: Uptimekuma on Docker-SRV-MGM
          siteMonitor: https://uptime.home.soniiit.net
          icon: uptime-kuma.png
          widget:
            type: uptimekuma
            url: https://uptime.home.soniiit.net
            slug: homepage
    
    - Kubernetes:
      - Ceph Dashboard:
          href: https://192.168.178.23:8443
          icon: https://cdn.icon-icons.com/icons2/2699/PNG/512/ceph_logo_icon_170406.png
          description: Ceph Dashboard on K3S-SONIIIT
          siteMonitor: https://192.168.178.23:8443/
      - Portainer:
          href: https://portainer.dev.soniiit.net
          icon: portainer.png
          siteMonitor: https://portainer.dev.soniiit.net
          widget:
            type: portainer
            url: https://portainer.dev.soniiit.net
            env: 1
            key: 
      - Rancher:
          href: https://rancher.dev.soniiit.net
          icon: https://www.rancher.com/assets/img/favicon.png
          siteMonitor: https://rancher.dev.soniiit.net
      - Traefik:
          href: https://traefik.dev.soniiit.net/dashboard/
          icon: https://icon.icepanel.io/Technology/svg/Traefik-Proxy.svg
          siteMonitor: https://traefik.dev.soniiit.net
          widget:
            type: traefik
            url: http://traefik.dev.soniiit.net
    
    - Services:
      - Gameserver:
          href: http://192.168.178.30
          icon: https://www.git.je/Alex/Pterodactyl-Panel/raw/commit/d2c770d21823c0f71ac14f30e9edd86eb5a15d16/public/favicons/android-icon-192x192.png
          description: Gameserver on APP-SRV-01
          siteMonitor: http://192.168.178.30
          widget:
            type: pterodactyl
            url: http://192.168.178.30
            key: 
    
    - IoT and Smarthome:
      - Home Assistant:
          href: https://homeassistant.soniiit.net
          icon: home-assistant.png
          description: Homeassistant on Docker-SRV-01
          siteMonitor: https://homeassistant.soniiit.net
          widget:
            type: homeassistant
            url: https://homeassistant.soniiit.net
            key: 
            custom:
