# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: My Awesome Homepage
headerStyle: boxed

background:
  image: images/4024286.png
  blur: sm
  brightness: 90
  opacity: 60

cardBlur: sm

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Networking:
    icon: mdi-network-#FFFFFF
  Infrastructure and Data:
    icon: mdi-server-#FFFFFF
  Management:
    icon: mdi-auto-fix-#FFFFFF
  Monitoring:
    icon: mdi-list-status-#FFFFFF
  Services:
    icon: mdi-cog-#FFFFFF
  IoT and Smarthome:
    icon: mdi-home-#FFFFFF
  Kubernetes:
    icon: mdi-kubernetes-#FFFFFF
