    - resources:
        cpu: false
        memory: false
    
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          hourCycle: h23
    
    - search:
        provider: google
        target: _blank
    
    - logo:
        icon: https://2.gravatar.com/userimage/251867332/d1c6638aadab2c616ffd2581061f0711?size=600
