- name: Longhorn bekannte Probleme beheben
  hosts: k3s_cluster
  become: true

  tasks:
    - name: iscsi_tcp Modul laden
      community.general.modprobe:
        name: iscsi_tcp
        state: present

    - name: iscsid Service starten
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: yes

    - name: nfs-common installieren
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: multipathd Service und Socket deaktivieren
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - multipathd
        - multipathd.socket
