- name: Longhorn bekannte Probleme beheben
  hosts: k3s_cluster
  become: true

  tasks:
    - name: Modprobe iscsi_tcp laden
      ansible.builtin.shell:
        cmd: modprobe iscsi_tcp

    - name: iscsi_tcp zum automatischen Laden hinzufügen
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: iscsi_tcp
        create: yes

    - name: Enable ISCSI Service
      ansible.builtin.shell:
        cmd: systemctl enable iscsid

    - name: Start ISCSI Service
      ansible.builtin.shell:
        cmd: systemctl start iscsid

    - name: nfs-common installieren
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Modprobe dm_crypt laden
      ansible.builtin.shell:
        cmd: modprobe dm_crypt

    - name: dm_crypt zum automatischen Laden hinzufügen
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: dm_crypt
        create: yes

    - name: multipathd Service und Socket deaktivieren
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - multipathd
        - multipathd.socket
