apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
type: Opaque
stringData:
  token: TokenHere # be sure you are generating an API token and not a global API key https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
