http:
  routers:
    jellyfin-route:
      rule: "Host(`jellyfin.home.soniiit.net`)"
      service: jellyfin-service
      entryPoints:
      - websecure
      tls:
        certResolver: cloudflare

  services:
    jellyfin-service:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
        - url: "http://192.168.178.21:8096"

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
