http:
  routers:
    kestra-route:
      rule: "Host(`kestra.home.soniiit.net`)"
      service: kestra-service
      entryPoints:
      - websecure
      tls:
        certResolver: cloudflare

  services:
    kestra-service:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
        - url: "http://192.168.178.20:1337"

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
