http:
  routers:
    traefik-02-route:
      rule: "Host(`traefik-02.home.soniiit.net`)"
      service: traefik-02-service
      entryPoints:
      - websecure
      tls:
        certResolver: cloudflare

  services:
    traefik-02-service:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
        - url: "http://192.168.178.22:9090"

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
