apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: crowdsec-bouncer-traefik-plugin
    namespace: traefik
spec:
    plugin:
        crowdsec-bouncer-traefik-plugin:
            CrowdsecLapiKey: LAPIKEY
            Enabled: "true"
