version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/docker/nginx-rp:/tmp/docker.sock:ro"

  whoami:
    image: jwilder/whoami:latest
    expose:
      - "8000"
    environment:
      - "VIRTUAL_HOST=whoami.local"
      - "VIRTUAL_PORT=8000"