- name: Cleanup Docker on Docker hosts
  hosts: docker
  become: yes
  tasks:
    - name: Set DOCKER_HOST for each host
      set_fact:
        docker_host: "tcp://{{ ansible_host }}:2375"

    - name: Prune non-dangling images on each Docker host
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
      environment:
        DOCKER_HOST: "{{ docker_host }}"
      vars:
        ansible_command_timeout: 300