- name: Update and upgrade apt packages
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
  become: yes

  tasks:
  - name: Update packages with apt
    when: ansible_pkg_mgr == 'apt'
    ansible.builtin.apt:
      update_cache: true

  - name: Upgrade packages with apt
    when: ansible_pkg_mgr == 'apt'
    ansible.builtin.apt:
      upgrade: dist
