apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: graylog
  namespace: graylog
  annotations: 
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`graylog.home.soniiit.net`)
      kind: Rule
      services:
        - name: my-graylog-web
          port: 9000
  tls:
    secretName: home-soniiit-net-selfsigned-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-soniiit-net-selfsigned
  namespace: graylog
spec:
  secretName: home-soniiit-net-selfsigned-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - "graylog.home.soniiit.net"
