version: "3.3"
services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_SCHEDULE=0 0 21 * * *
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://DISCORD_TOKEN@DISCORD_ID?splitlines=no
      - WATCHTOWER_NOTIFICATION_TEMPLATE={{range .}}[{{.Level}}] {{.Message}}{{println}}{{end}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    restart: unless-stopped
networks: {}