name: "Update Twingate Records"

on:
  push:
    branches:
      - main
    paths:
      - 'App/Terraform/application/twingate/*.tf'
  workflow_dispatch:

jobs:
  send_twingate_update:
    runs-on: self-hosted
    steps:
      # send webhook to update DNS records
      - name: Send Twingate Update Webhook
        run: |
          curl --insecure ${{ secrets.WEBHOOK_URL_TWINGATE_UPDATE_KESTRA }}
